### ISSUE TITLE
Top Mask Attack - Mask Generation Fails

### ISSUE THREAD

**Issue by cclements** [trustedsec/hate_crack#25]
Running into the following issue.  Let me know what other info I can provide:
```
python hate_crack.py /root/ntlm.txt 1000


  ___ ___         __             _________                       __
 /   |   \_____ _/  |_  ____     \_   ___ \____________    ____ |  | __
/    ~    \__  \\   __\/ __ \    /    \  \/\_  __ \__  \ _/ ___\|  |/ /
\    Y    // __ \|  | \  ___/    \     \____|  | \// __ \\  \___|    <
 \___|_  /(____  /__|  \___  >____\______  /|__|  (____  /\___  >__|_ \
       \/      \/          \/_____/      \/            \/     \/     \/
                          Version 1.06

PWDUMP format detected...
Parsing NT hashes...
Parsing LM hashes...
LM hashes identified. Would you like to brute force the LM hashes first? (Y) N

        (1) Quick Crack
        (2) Extensive Pure_Hate Methodology Crack
        (3) Brute Force Attack
        (4) Top Mask Attack
        (5) Fingerprint Attack
        (6) Combinator Attack
        (7) Hybrid Attack
        (8) Pathwell Top 100 Mask Brute Force Crack
        (9) PRINCE Attack
        (10) YOLO Combinator Attack
        (11) Middle Combinator Attack
        (12) Thorough Combinator Attack

        (96) Export Output to Excel Format
        (97) Display Cracked Hashes
        (98) Display README
        (99) Quit

Select a task: 4

Enter a target time for completion in hours (4):
Traceback (most recent call last):
  File "/root/tools/hate_crack/PACK/statsgen.py", line 302, in <module>
    statsgen.print_stats()
  File "/root/tools/hate_crack/PACK/statsgen.py", line 197, in print_stats
    self.filter_counter * 100 / self.total_counter, self.filter_counter, self.total_counter)
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/root/tools/hate_crack/PACK/maskgen.py", line 312, in <module>
    maskgen.generate_masks(sorting_mode)
  File "/root/tools/hate_crack/PACK/maskgen.py", line 136, in generate_masks
    sample_occurrence * 100 / self.total_occurrence, sample_occurrence, self.total_occurrence)
ZeroDivisionError: division by zero
hashcat (v5.0.0) starting...

OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: GeForce GTX 1080 Ti, 2793/11175 MB allocatable, 28MCU

Invalid mask.

Started: Thu Nov  1 10:40:48 2018
Stopped: Thu Nov  1 10:40:49 2018
```

**Comment by bandrel** [comment]
We should include some better error messaging around this. If you have not cracked any passwords from ntlm.txt you will get this error, but it is to be expected because there was nothing to run stats on to generate the masks.

**Comment by cclements** [comment]
Makes sense, appreciate the follow up!
